AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation Template for Cloud Programming Assignment 1
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ec2rsa
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/32
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  EC2SecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: Home SSH Access Security Group
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref SSHLocation
  EC2A:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: 'us-east-1c'
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: ami-067d1e60475437da2
      Tags:
        - Key: Name
          Value: EC2A
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          #update packages
          sudo dnf update
          #install java
          sudo dnf -y install java-17-amazon-corretto-headless
          #get jar file from s3
          wget http://cloudprogramminghw1jarfiles.s3.amazonaws.com/CloudProgrammingAssignment-EC2A.jar -O /home/ec2-user/EC2A.jar
          #create credentials and config file
          mkdir /home/ec2-user/.aws
          touch /home/ec2-user/.aws/credentials
          touch /home/ec2-user/.aws/config
          echo [default] >> /home/ec2-user/.aws/config
          echo region=us-east-1 >> /home/ec2-user/.aws/config
          chown -R ec2-user:ec2-user /home/ec2-user
  EC2B:
    Type: 'AWS::EC2::Instance'
    Properties:
      AvailabilityZone: 'us-east-1c'
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: ami-067d1e60475437da2
      Tags:
        - Key: Name
          Value: EC2B
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          #update packages
          sudo dnf update
          #install java
          sudo dnf -y install java-17-amazon-corretto-headless
          #get jar file from s3
          wget http://cloudprogramminghw1jarfiles.s3.amazonaws.com/CloudProgrammingAssignment-EC2B.jar -O /home/ec2-user/EC2B.jar
          #create credentials and config file
          mkdir /home/ec2-user/.aws
          touch /home/ec2-user/.aws/credentials
          touch /home/ec2-user/.aws/config
          echo [default] >> /home/ec2-user/.aws/config
          echo region=us-east-1 >> /home/ec2-user/.aws/config
          #reset permissions
          chown -R ec2-user:ec2-user /home/ec2-user
  PictureQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      FifoQueue: 'true'
      QueueName: picturequeue.fifo
      ReceiveMessageWaitTimeSeconds: 20
      VisibilityTimeout: 60
Outputs:
  EC2AURL:
    Description: URL for newly created EC2A instance
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - EC2A
          - PublicDnsName
  EC2BURL:
    Description: URL for newly created EC2B instance
    Value: !Join 
      - ''
      - - 'http://'
        - !GetAtt 
          - EC2B
          - PublicDnsName
